# Generated by Django 6.0.1 on 2026-03-25 16:48

import backend.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Original filename', max_length=255)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to=backend.models.user_csv_upload_path)),
                ('analytics_json', models.JSONField(help_text='Pre-computed analytics payload returned to the frontend')),
                ('source_currency', models.CharField(default='USD', max_length=10)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='The dataset the user currently sees on their dashboard')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
